sudo: required

language: node_js
node_js:
  - "node"

env:
  global:
    - VERSION=$(git describe | sed s/v//g)
  matrix:
    - ARCH=x86_64
      DOCKER_BUILD=ryandterri/ercot-price-service:${VERSION}
      DOCKERFILE=Dockerfile
    - ARCH=arm
      DOCKER_BUILD=ryandterri/arm32v6-ercot-price-service:${VERSION}
      DOCKERFILE=Dockerfile.arm32v6
services:
  - docker

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t ${DOCKER_BUILD} -f ${DOCKERFILE} .

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} || false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker push ${DOCKER_BUILD} || false'

branches:
  only:
    - master